#!/bin/sh

# Set these paths appropriately

BIN="/root/find-toponym/treetagger/bin"
CMD="/root/find-toponym/treetagger/cmd"
LIB="/root/find-toponym/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
