#!/bin/sh

# Set these paths appropriately

BIN="./treetagger/bin"
CMD="./treetagger/cmd"
LIB="./treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
