#!/bin/sh

# Set these paths appropriately

BIN="/root/find-toponym/treetagger/bin"
CMD="/root/find-toponym/treetagger/cmd"
LIB="/root/find-toponym/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
