#!/bin/sh

# Set these paths appropriately

BIN="/root/find-toponym/treetagger/bin"
CMD="/root/find-toponym/treetagger/cmd"
LIB="/root/find-toponym/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/hungarian-abbreviations
PARFILE=${LIB}/hungarian.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
