#!/bin/sh

# Set these paths appropriately

BIN="/root/find-toponym/treetagger/bin"
CMD="/root/find-toponym/treetagger/cmd"
LIB="/root/find-toponym/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/galician-abbreviations
PARFILE=${LIB}/galician.par
MWLFILE=${LIB}/galician-mwls

$TOKENIZER -z -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
